==== Using lsof to review network connections and daemons:
* View all network releated connections (associates file descriptor to socket): `lsof -i`
** Can use `-i4` or `-i6` to limit output to v4 or v6
** Can limit to a port range: `lsof -i :<begining port>-<ending port>`
** Very good test to see what IP's dnsmasq is listening on: `sudo lsof -i4 | grep dnsmasq`
*** NOTE: Even if dnsmasq is listening on multiple IPs, it's configuration may limit processing requests from select interfaces

==== Wait for something to happen before moving on:
* Wait for ssh to be ready after rebooting a remote host: `until nc -zv $host 22; do sleep 5; done`
* Wait for NFS server to be ready: `until sudo showmount -e; do echo "NFS server not ready" && sleep 5; done`


* To see the ports being monitored on the host: `ss -npr --listening`

.nmap (probing from external system)
* Check if a server is running DNS: `sudo nmap -sT -sU -p 53 <server IP>`
* Check if a server is running DHCP: `sudo nmap -sU -p 67 --script=dhcp-discover <server IP>`
** Check for DHCP servers on a subnet: `sudo nmap -sU -p 67 --script=dhcp-discover <network>/<CIDR mask> | less`
** Note that a result of "67/udp open|filtered dhcps" means the port is monitored but the DHCP server is not responding to requests
** Example of a valid DHCP server response:
----
67/udp open  dhcps
| dhcp-discover:
|   DHCP Message Type: DHCPACK
|   Server Identifier: 192.168.1.10
|   Broadcast Address: 192.168.1.255
|   Domain Name: example.com
|   Domain Name Server: 192.168.1.10
|   Router: 192.168.1.1
|_  Subnet Mask: 255.255.255.0
MAC Address: 52:54:00:93:EB:A1
----

* Can also use `telnet <server IP> <port>` to test for an open TCP port


=== tcpdump

* `sudo zypper -n install tcpdump`

* `sudo tcpdump -i virbr0 -n src host 10.110.2.0`
** Viewing NAT traffic on a bridge that originates (src) from a VM with IP 10.110.2.0
** -n = don't resolve hostname, -nn = don't resolve hostname or port

=== xip.io

* Public DNS server that provides wildcard DNS resolution for the IP address that is embedded in the FQDN
* I.e:
----
getent hosts 172.16.240.100.xip.io
172.16.240.100  172.16.240.100.xip.io
----
----
getent hosts test.172.16.240.100.xip.io
172.16.240.100  test.172.16.240.100.xip.io
----
----
getent hosts foo.bar.172.16.240.100.xip.io
172.16.240.100  foo.bar.172.16.240.100.xip.io
----


// vim: set syntax=asciidoc:
