.eval command:
* Can be used to create a variable that contains a command set and then execute the command set later, i.e. 
as the result of conditional test.
----
/home/user1 > a="ls | more"
/home/user1 > $a
bash: command not found: ls | more
/home/user1 > # Above command didn't work as ls tried to list files with names "|" (pipe) and "more". 
/home/user1 > # But these files do not exist.
/home/user1 > eval $a
file.txt
mailids
remote_cmd.sh
sample.txt
tmp
/home/user1 >
----

* Also seems to execute the output of a command:
----
sles@admin:~/caaspv4-cluster> ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-X5GHuyKyv9WL/agent.21418; export SSH_AUTH_SOCK;
SSH_AGENT_PID=21419; export SSH_AGENT_PID;
echo Agent pid 21419;
----
** The output of ssh-agent shows the variables that need to be set

----
sles@admin:~/caaspv4-cluster> eval "$(ssh-agent)"
Agent pid 21425
----
** eval runs those commands, including the final echo


.Using sed to search for one string on a line, then modify a different part of the line:
* The command below searches for lines beginning with a space, then adds a # at the beginning of the line
`sed -e '/^\ / s/^#*/#/' <file>`
* Comment lines two through four, no matter what those lines contain (in-place edit): `sed -i '2,4 s/^/#/' <file>`
* Search for the line that begins with 127 and then remove localhost (outputs updated file contents to stdout, does not update file): `sed -e '/^127/ s/localhost//' /etc/hosts`
* Search for the line that begins with 127, remove localhost, then insert a new line under it with the string that follows the "/a" (use "/i" for insert above the line returned by the search string) (outputs updated file contents to stdout, does not update file): 
** `sed -e '/^127/ s/localhost//' -e '/^127/a 172.16.200.132    ses-osd-c.stable.suse.lab    ses-osd-c    localhost' /etc/hosts`
*** Note that the single quotes will prevent variable expansion
* if you want to insert multiple lines, you can use ‘\n’ as shown below.

`sed '/^anothervalue=.*/i before=me\nbefore2=me2' test.txt`

