==== Working with hardened, minimized, and JeOS images:
* A lot of functions require the `kernel-default` package `kernel-default-base` won't provide all of the needed pieces
** The resultant errors are nearly useless
** Examples are 802.11q VLANS and NFS server
** For automated deployments can try to add something like: `zypper in --force-resolution --no-confirm --force kernel-default`
** Basically if something pretty simple doesn't work, look for the `kernel-default` package.

==== To find and activate a repo for a specific package

* On a system that has the same release and SP version and has the package/command:
** To find the package that contains a command: `cnf <command>`
** `zypper search-packages <package>`
*** This gives the "SUSEConnect Activation Command" to activate the repo

* Run the "SUSEConnect Activation Command" as root on the target system

.To View an installed package, including revision:
* `zypper se --details --installed <package>`
** Can use `zypper se --details <package>` to see in same thing but for packages that are not yet installed
* To query all packages installed: `rpm -qa`
* To query all files contained in a package: `rpm -ql`

* To find packages based on what product they are in, use: https://scc.suse.com/packages
** Good for finding which repository is needed to be enabled to get the package
** Can also find patches under "My Tools" on the left side of the same website

==== VM images can sometimes lose eth0 and or other interfaces after updating
* Remove /etc/udev/rules.d/70-persistent-net.rules and reboot

==== RMT Server
* `sudo yast rmt` to configure the base server. Doesn't do anything with repos.
* `sudo rmt-cli sync` to sync (not mirror) repos from SCC

.Adding product repos:
* `sudo rmt-cli product list --all`
** `sudo rmt-cli product list --all | grep -i <product>`
*** The furthest left column is the product ID
* `sudo rmt-cli product enable <product ID>`
* `sudo rmt-cli sync`
* `sudo rmt-cli mirror`

*** Seems like you can do the same to enable individual repos by just replacing "product" with "repo" in the commands above.

==== Reset root password:
* Stop boot at GRuB screen with arrow keys
* Highlight the default boot line and press `e`
* Scroll down to the line that starts with `linux     /boot/vmlinuz` or `kernel     /boot/vmlinuz` and go the end of that line (the End key is helpful here)
* Add a space, then `init=/bin/bash`
* Press Ctrl+x or F10 to boot (on older systems it might be `b`)
* At the root shell can review the /etc/shadow file to see what accounts exist on the system and if they have a password assigned
** `*` means that there is no password assigned and thus the user cannot login with password based authentication
** `!` or a password that starts with `!` means the account is locked and the user cannot login
* Can use the `passwd` command to create a password for root or any other account
* Only BASH functions are available so can't do much more that change passwords and edit files
* Have to externally reset the system

// vim: set syntax=asciidoc:
