
.scp
* Can specify a source and destination that are not the current host
** I.e. scp between two servers from your workstation
** Use option `-3` to make the scp go through the current host. Useful when the two hosts can't communicate directly.

.Create a file of regenerated hostnames (.all_nodes) and use ssh-keyscan to populate the /etc/ssh/ssh_known_hosts file:
----
sudo bash -c "ssh-keyscan -f .all_nodes > /etc/ssh/ssh_known_hosts"
----
* Note that it can still break if the user's known_hosts file has conflicts
** Use `ssh-keygen -R <hostname as it appears in the known_hosts file>` to remove conflicts
*** May have to repeat to remove IP address entries

.Ignore entries in ~/.ssh/known_hosts for a specific host
* Breaks a big part of SSH security
* Useful for testing (i.e. Terraform) where hostnames are reused but new instances are generated regularly
* In the ~/.ssh/config file:
----
Host <your problematic host>
  StrictHostKeyChecking no
----
* Can add these as well to supress the error that still pops up:
----
  GlobalKnownHostsFile=/dev/null
  UserKnownHostsFile=/dev/null 
----

* Equivilent on the commandline: `ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${user}@${host}`

.Add to .bashrc to autocomplete hosts in .ssh/known_hosts for ssh:
----
complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | \
    sed -e s/,.*//g | uniq | grep -v "\["`;)" ssh
----

.Verify the SHA256 has of a hosts sshd daemon (run on the host):
----
for pubkey_file in /etc/ssh/*.pub; do ssh-keygen -lf ${pubkey_file} -E sha256;  done
----
* If one of the keys returned doesn't match what your ssh session is showing for that host, something is very wrong!

// vim: set syntax=asciidoc:


